<?php include_once '../createuser.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-15 at 12:27:26.
 */
class CreateUserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CreateUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreateUser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CreateUser::getuserinfo
     * @todo   Implement testGetuserinfo().
     */
    

    /**
     * @covers CreateUser::GetUser
     * @todo   Implement testGetUser().
     */
    public function testGetUser1() {
        // Remove the following lines when you implement this test.
        $name = "thomas";
        $pass = "1234";
        $cname = "toto";
       
        //$func = $this->object->GetUser($name, $pass, $cname);
        $this->assertTrue($this->object->GetUser($name, $pass, $cname));        
    }
    public function testGetUser2() {
        // Remove the following lines when you implement this test.
        $name = "123";
        $pass = "123";
        $cname = "123";
       
        //$func = $this->object->GetUser($name, $pass, $cname);
        $this->assertFalse($this->object->GetUser($name, $pass, $cname));        
    }
    public function testGetUser3() {
        // Remove the following lines when you implement this test.
        $name = "tete";
        $pass = "tete";
        $cname = "tete";
       
        //$func = $this->object->GetUser($name, $pass, $cname);
        $this->assertFalse($this->object->GetUser($name, $pass, $cname));        
    }

}
