<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-15 at 11:02:15.
 */
class logicTest extends PHPUnit_Framework_TestCase {

    /**
     * @var logic
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new logic;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers logic::getthreemeals
     * @todo   Implement testGetthreemeals().
     */
    public function testGetthreemeals() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers logic::getmeal
     * @todo   Implement testGetmeal().
     */
    public function testGetmeal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers logic::getingredients
     * @todo   Implement testGetingredients().
     */
    public function testGetingredients() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
