<?php include '../userverification.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-15 at 19:25:36.
 */
class UserVerificationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var UserVerification
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserVerification;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers UserVerification::getUserInfo
     * @todo   Implement testGetUserInfo().
     */
    public function testGetUserInfo()
    {
        // assert login is sucessfull
        $username = "test";
        $password = "1111";
        
       
        //$func = $this->object->GetUser($name, $pass, $cname);
        $this->assertTrue($this->object->GetUser($username, $password)); 
    }

    /**
     * @covers UserVerification::GetUser
     * @todo   Implement testGetUser().
     */
    public function testGetUser()
    {
        //assume user doesnt excist
        $username = "test";
        $password = "2222";
        
       
        //$func = $this->object->GetUser($name, $pass, $cname);
        $this->assertFalse($this->object->GetUser($username, $password)); 
    }
    
    public function testPasswordIsString()
    {
        //assume user uses string as password
        $username = "test";
        $password = "test";
        
       
        //$func = $this->object->GetUser($name, $pass, $cname);
        $this->assertEquals("Your Password needs to be a number",$this->object->GetUser($username, $password)); 
    }
    
    
}
